### ISSUE TITLE
Question about the commit

### ISSUE THREAD

**Issue by nieyuyao** [share/sharedb-mongo#126]
Why write the op before snapshot, is there any consideration?

https://github.com/share/sharedb-mongo/blob/9e88c28ee15a9cfbcf9e7aa9a74415e7c62fda15/index.js#L239-L254

**Comment by alecgibson** [comment]
I think this is done like this because back in MongoDB 3, there wasn't support for [transactions](https://www.mongodb.com/docs/manual/core/transactions/), so something always needed to be written first, and ops were chosen.

There's a bit of a writeup on the behaviour in the [`README`](https://www.mongodb.com/docs/manual/core/transactions/).

**Comment by nieyuyao** [comment]
@alecgibson Thanks for your reply. But i still have a question, can i write the snapshot before op?

**Comment by alecgibson** [comment]
If you're talking about an implementation that you're doing yourself, there's no reason why not, so long as you ensure that you have some way to ensure the op being written is "canonical", and that you don't have conflicting snapshot writes.

As I mentioned above, a new implementation might use MongoDB transactions, although this may not be as performant; there's some (light) discussion on the topic in https://github.com/share/sharedb-mongo/issues/127
