### ISSUE TITLE
Support other databases PostgreSQL etc.

### ISSUE THREAD

**Issue by riston** [share/sharedb-mongo#24]
What would be the minimal adapter code to support some other database engine with the sharedb? Is it possible to implement it similarly to livedb only the core functions without all the querying and projection functions ? 

The livedb-postgres (https://github.com/usecanvas/livedb-postgresql/blob/master/index.js) module.

**Comment by nateps** [comment]
Yes, this is something we'd love to support. This issue really belongs on https://github.com/share/sharedb/issues. Would you mind creating an issue there specifically for creating a PostgresSQL adapter? We should have an issue per datastore.

Also, we should have a separate issue to track documentation of the adapter API. The MemoryDB, which is implemented in ShareDB and used for unit tests is a pretty good minimal example until the docs are written: https://github.com/share/sharedb/blob/master/lib/db/memory.js In short, for a minimal implementation, you must define all the public methods in that file (close, commit, getSnapshot, getOps, and query). The remaining methods are for making implementations more efficient.

Closing this issue, since we should create them against sharedb.
