### ISSUE TITLE
escape illegal mongo characters on storage/retrieval

### ISSUE THREAD

**Issue by atsepkov** [share/sharedb-mongo#51]
Mongo can't have `.` or `$` in key name, ShareDB can. This results in the following error when storing keys with dots in sharedb if sharedb-mongo is used as the backend:

    Uncaught Error: The dotted field 'ScreenShot2017-03-24at1.44.18PM' in 'tags.ScreenShot2017-03-24at1.44.18PM' is not valid for storage.

Forcing the user to handle this workaround is not ideal, since it's an internal implementation detail occurring at a layer that the user should not be touching. Is it possible to add the fix for this in sharedb-mongo directly, perhaps the one suggested here: http://stackoverflow.com/questions/12397118/mongodb-dot-in-key-name ?

**Comment by alecgibson** [comment]
Since MongoDB 3.6, field names [can contain `.` and `$`](https://docs.mongodb.com/manual/reference/limits/#mongodb-limit-Restrictions-on-Field-Names).

Constructing valid MongoDB field names also isn't currently considered a concern of this library; `sharedb` is a relatively "low-level" library, and consumers are expected to construct their objects with an understanding of how the underlying database (MongoDB in this case) acts.
